const Specialties = [
  "Audiologist",
  "Allergist",
  "Anesthesiologist",
  "Cardiologist",
  "Dentist",
  "Dermatologist",
  "Endocrinologist",
  "Epidemiologist",
  "Gynecologist",
  "Immunologist",
  "Infectious Disease Specialist",
  "Internal Medicine Specialist",
  "Medical Geneticist",
  "Microbiologist",
  "Neonatologist",
  "Neurologist",
  "Neurosurgeon",
  "Obstetrician",
  "Oncologist",
  "Orthopedic Surgeon",
  "ENT Specialist",
  "Pediatrician",
  "Physiologist",
  "Plastic Surgeon",
  "Podiatrist",
  "Psychiatrist",
  "Radiologist",
  "Rheumatologist",
  "Surgeon",
  "Urologist",
];

export default Specialties;
