const Symptoms = () => [
  "aging, premature",
  "fever",
  "hypothermia",
  "body weight",
  "birth weight",
  "weight loss",
  "cyanosis",
  "muscle hypertonia",
  "muscle rigidity",
  "muscle weakness",
  "quadriplegia",
  "reflex, abnormal",
  "seizures",
  "abdominal pain",
  "anorexia",
  "diarrhea, infanti",
  "nausea",
  "anoxia",
  "apnea",
  "cough",
  "dyspnea",
  "hemoptysis",
  "hypercapnia",
  "hyperventilation",
  "respiratory aspir",
  "respiratory sound",
  "proteinuria",
  "weight gain",
  "cachexia",
  "obesity",
  "edema",
  "paralysis",
  "hearing disorders",
  "hearing loss",
  "hearing loss, con",
  "hearing loss, sen",
  "sleep disorders",
  "sleep deprivation",
  "oral manifestatio",
  "diarrhea",
  "hyperoxia",
  "sneezing",
  "asthenia",
  "fever of unknown ",
  "fetal macrosomia",
  "emaciation",
  "overweight",
  "obesity, morbid",
  "thinness",
  "cardiac output, l",
  "hydrops fetalis",
  "eye hemorrhage",
  "fatigue",
  "fetal distress",
  "hot flashes",
  "hypergammaglobuli",
  "mobility limitati",
  "cerebrospinal flu",
  "dyskinesias",
  "ataxia",
  "cerebellar ataxia",
  "gait ataxia",
  "athetosis",
  "chorea",
  "dystonia",
  "hyperkinesis",
  "hypokinesia",
  "myoclonus",
  "psychomotor agita",
  "akathisia, drug-i",
  "tics",
  "tremor",
  "gait disorders, n",
  "meningism",
  "apraxias",
  "catatonia",
  "communication dis",
  "language disorder",
  "dyslexia",
  "alexia, pure",
  "language developm",
  "speech disorders",
  "aphasia",
  "aphasia, broca",
  "dysarthria",
  "learning disorder",
  "confusion",
  "delirium",
  "consciousness dis",
  "unconsciousness",
  "coma",
  "syncope",
  "memory disorders",
  "amnesia",
  "mental retardatio",
  "auditory perceptu",
  "hallucinations",
  "psychomotor disor",
  "muscle cramp",
  "muscle spasticity",
  "muscle hypotonia",
  "muscular atrophy",
  "myotonia",
  "tetany",
  "pain",
  "back pain",
  "low back pain",
  "facial pain",
  "headache",
  "neck pain",
  "neuralgia",
  "neuralgia, posthe",
  "sciatica",
  "pain, intractable",
  "facial paralysis",
  "gastroparesis",
  "hemiplegia",
  "ophthalmoplegia",
  "ophthalmoplegia, ",
  "paraplegia",
  "pseudobulbar pals",
  "respiratory paral",
  "vocal cord paraly",
  "paresis",
  "paraparesis",
  "paraparesis, spas",
  "psychophysiologic",
  "sensation disorde",
  "dizziness",
  "deafness",
  "hearing loss, bil",
  "hearing loss, noi",
  "tinnitus",
  "olfaction disorde",
  "somatosensory dis",
  "hyperalgesia",
  "hyperesthesia",
  "hypesthesia",
  "paresthesia",
  "taste disorders",
  "dysgeusia",
  "vision disorders",
  "blindness",
  "blindness, cortic",
  "color vision defe",
  "diplopia",
  "hemianopsia",
  "vision, low",
  "urinary bladder, ",
  "vertigo",
  "voice disorders",
  "hoarseness",
  "oral hemorrhage",
  "abdomen, acute",
  "colic",
  "arthralgia",
  "chest pain",
  "angina pectoris",
  "acute coronary sy",
  "angina, unstable",
  "earache",
  "toothache",
  "pain, postoperati",
  "pelvic pain",
  "constipation",
  "dyspepsia",
  "flatulence",
  "heartburn",
  "hiccup",
  "hyperphagia",
  "bulimia",
  "vomiting",
  "hematemesis",
  "mouth breathing",
  "snoring",
  "ecchymosis",
  "jaundice",
  "jaundice, obstruc",
  "pruritus",
  "tinea pedis",
  "purpura",
  "purpura, schoenle",
  "purpura, thromboc",
  "purpura, thrombot",
  "hypercalciuria",
  "polyuria",
  "albuminuria",
  "hemoglobinuria",
  "urinary incontine",
  "virilism",
  "neurologic manife",
  "torticollis",
  "aphasia, wernicke",
  "stuttering",
  "gerstmann syndrom",
  "illusions",
  "phantom limb",
  "spasm",
  "reflex, babinski",
  "hearing loss, cen",
  "hearing loss, sud",
  "hyperacusis",
  "shoulder pain",
  "fetal hypoxia",
  "skin manifestatio",
  "body weight chang",
  "chills",
  "edema, cardiac",
  "mental fatigue",
  "feminization",
  "flushing",
  "intermittent clau",
  "motion sickness",
  "syncope, vasovaga",
  "lethargy",
  "perceptual disord",
  "trismus",
  "pupil disorders",
  "horner syndrome",
  "scotoma",
  "angina pectoris, ",
  "reticulocytosis",
  "postoperative nau",
  "hyperemesis gravi",
  "vomiting, anticip",
  "dyspnea, paroxysm",
  "hypoventilation",
  "livedo reticulari",
  "dysuria",
  "hirsutism",
  "hearing loss, hig",
  "dysphonia",
  "glossalgia",
  "halitosis",
  "cafe-au-lait spot",
  "cardiac output, h",
  "eye manifestation",
  "heart murmurs",
  "hearing loss, uni",
  "amblyopia",
  "photophobia",
  "pseudophakia",
  "pallor",
  "waterhouse-frider",
  "oliguria",
  "flank pain",
  "fetal weight",
  "mutism",
  "hearing loss, mix",
  "amaurosis fugax",
  "purpura, hyperglo",
  "persistent vegeta",
  "sarcopenia",
  "presbycusis",
  "prostatism",
  "pain, referred",
  "brown-sequard syn",
  "dysmenorrhea",
  "cheyne-stokes res",
  "labor pain",
  "articulation diso",
  "gagging",
  "supranuclear pals",
  "agnosia",
  "fasciculation",
  "metatarsalgia",
  "ageusia",
  "aphonia",
  "purpura fulminans",
  "gait apraxia",
  "neurobehavioral m",
  "orthostatic intol",
  "hypocapnia",
  "prosopagnosia",
  "anisocoria",
  "korsakoff syndrom",
  "decerebrate state",
  "miosis",
  "necrolytic migrat",
  "synkinesis",
  "hemifacial spasm",
  "hearing loss, fun",
  "agraphia",
  "dyslexia, acquire",
  "deaf-blind disord",
  "usher syndromes",
  "catalepsy",
  "anomia",
  "aphasia, conducti",
  "aphasia, primary ",
  "stupor",
  "amnesia, anterogr",
  "amnesia, retrogra",
  "apraxia, ideomoto",
  "tonic pupil",
  "encopresis",
  "echolalia",
  "aerophagy",
  "eructation",
  "amnesia, transien",
  "myokymia",
  "primary progressi",
  "coprophagia",
  "nocturia",
  "renal colic",
  "urinoma",
  "systolic murmurs",
  "striae distensae",
  "morning sickness",
  "eye pain",
  "sweating sickness",
];
export default Symptoms();
